controller_manager:
  ros__parameters:
    update_rate: 100    # Hz

    # Publish all joint states -----------------------------------
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # Position Controllers --------------------------------------
