manipulator:
  inertial:
    origin:
      rpy: "0 0 0"
      xyz: "0 0 0"
    mass: "0.01"
    inertia:
      ixx: "0.0001"
      ixy: "0.0"
      ixz: "0.0"
      iyy: "0.0001"
      iyz: "0.0"
      izz: "0.0001"
  visual:
    origin:
      rpy: "3.14 0 0"
      xyz: "-0.035 0.032 0.0306"
    geometry:
      mesh: "Klinke_v2/klinke_v2_collision.stl"
      scale: "0.001 0.001 0.001"
    material: "silver"
  collision:
    origin:
      rpy: "0 0 0"
      xyz: "0 0 0"
    geometry:
      mesh: "Klinke_v2/klinke_v2_visual.stl"
      scale: "0.001 0.001 0.001"
  
  joints:
    attachment_joint:
      origin:
        rpy: "0.0 0.0 0.0"
        xyz: "0.0 0.0 0.0"