box:
  inertial:
    origin:
      rpy: "0.0 0.0 0.0"
      xyz: "-0.1865 0.284 0.0944268"
    mass: "30.0"
    inertia:
      ixx: "0.895724206"
      ixy: "0.0"
      ixz: "0.0"
      iyy: "0.436986706"
      iyz: "0.0"
      izz: "1.1543825"
  visual:
    origin:
      rpy: "0 0 0"
      xyz: "0 0 0"
    geometry:
      mesh: "adapterbox_bf_tech_klein/visual/box_visual_v2.dae"
      scale: "0.01 0.01 0.01"
    material: "silver"
  collision:
    origin:
      rpy: "0 0 0"
      xyz: "0 0 0"
    geometry:
      mesh: "adapterbox_bf_tech_klein/collision/box_collision.stl"
      scale: "0.001 0.001 0.001"
  joints:
    cover_joint:
      origin:
        rpy: "0.0 0.0 0.0"
        xyz: "-0.289622 0.0595 0.291782"
      axis:
        xyz: "0.0 1.0 0.0"
      limit:
        effort: "100"
        lower: "-1.5708"
        upper: "0"
        velocity: "100"
    lever_joint:
      origin:
        rpy: "0 0 0"
        xyz: "-0.0540005 0.0 0.1030005"
      axis:
        xyz: "0.0 1.0 0.0"
      limit:
        effort: "100"
        lower: "0.0"
        upper: "3.141593"
        velocity: "100"
    cylinder_rod_left_joint:
      origin:
        rpy: "0 0.34906585 0"
        xyz: "-0.26 0.0495 0.26941"
      axis:
        xyz: "0 1 0"
      limit:
        effort: "100"
        lower: "-1.670796327"
        upper: "0.0"
        velocity: "100"
    cylinder_rod_right_joint:
      origin:
        rpy: "0 0.34906585 0"
        xyz: "-0.26 0.5185 0.26941"
      axis:
        xyz: "0 1 0"
      limit:
        effort: "100"
        lower: "-1.670796327"
        upper: "0.0"
        velocity: "100"

cover_frame:
  inertial:
    origin:
      rpy: "0.0 0.270526034 0.0"
      xyz: "0.1445855 0.2245 -0.05"
    mass: "2.5"
    inertia:
      ixx: "0.054616667"
      ixy: "0.0"
      ixz: "0.0"
      iyy: "0.020745208"
      iyz: "0.0"
      izz: "0.073655208"
  visual:
    origin:
      rpy: "0.0 1.308996939 0.0"
      xyz: "-0.20675 -0.0595 -0.3525"
    geometry:
      mesh: "adapterbox_bf_tech_klein/visual/cover_frame_visual.dae"
      scale: "0.01 0.01 0.01"
    material: "silver"
  collision:
    origin:
      rpy: "0.0 0.0 0.0"
      xyz: "0.289622 -0.0595 -0.291782"
    geometry:
      mesh: "adapterbox_bf_tech_klein/collision/cover_frame_collision.stl"
      scale: "0.001 0.001 0.001"
  joints:
    cylinder_body_left_joint:
      origin:
        rpy: "0 0.32 0"
        xyz: "0.2192 -0.0095 -0.094"
      axis:
        xyz: "0 1 0"
      limit:
        effort: "100"
        lower: "-1.570796327"
        upper: "0.0"
        velocity: "100"
    cylinder_body_right_joint:
      origin:
        rpy: "0 0.32 0"
        xyz: "0.2192 0.459 -0.094"
      axis:
        xyz: "0 1 0"
      limit:
        effort: "100"
        lower: "-1.570796327"
        upper: "0.0"
        velocity: "100"

lever:
  inertial:
    origin:
      rpy: "0.0 0.0 0.0"
      xyz: "-0.01 0.284 0.0"
    mass: "0.726499"
    inertia:
      ixx: "0.026650042"
      ixy: "0.0"
      ixz: "0.0"
      iyy: "0.000075677"
      iyz: "0.0"
      izz: "0.026650042"
  visual:
    origin:
      rpy: "0 0 0"
      xyz: "0.0125 -0.0475 -0.0125"
    geometry:
      mesh: "adapterbox_bf_tech_klein/visual/lever_visual.dae"
      scale: "0.01 0.01 0.01"
    material: "silver"
  collision:
    origin:
      rpy: "0 0 0"
      xyz: "0.0540005 -0.0 -0.1030005"
    geometry:
      mesh: "adapterbox_bf_tech_klein/collision/lever_collision.stl"
      scale: "0.001 0.001 0.001"

cylinder_body_left:
  inertial:
    origin:
      rpy: "0.0 0.0 0.0"
      xyz: "-0.07425 0.0 0.0"
    mass: "0.187778"
    inertia:
      ixx: "0.000008012"
      ixy: "0.0"
      ixz: "0.0"
      iyy: "0.000349083"
      iyz: "0.0"
      izz: "0.000349083"
  visual:
    origin:
      rpy: "0.0 1.082104136 0.0"
      xyz: "-0.357 -0.05 -0.3477"
    geometry:
      mesh: "adapterbox_bf_tech_klein/visual/cylinder_body_visual.dae"
      scale: "0.01 0.01 0.01"
    material: "silver"
  collision:
    origin:
      rpy: "0.0 -0.35 0.0"
      xyz: "0.1325 -0.05 -0.1625"
    geometry:
      mesh: "adapterbox_bf_tech_klein/collision/cylinder_body_collision.stl"
      scale: "0.001 0.001 0.001"
  joints:
    cylinder_left_joint:
      origin:
        rpy: "0 0 0"
        xyz: "0.2 0.0 0.0"
      axis:
        xyz: "1 0 0"
      limit:
        effort: "100"
        lower: "0.0"
        upper: "0.95"
        velocity: "100"

cylinder_body_right:
  inertial:
    origin:
      rpy: "0.0 0.0 0.0"
      xyz: "-0.07425 0.0 0.0"
    mass: "0.187778"
    inertia:
      ixx: "0.000008012"
      ixy: "0.0"
      ixz: "0.0"
      iyy: "0.000349083"
      iyz: "0.0"
      izz: "0.000349083"
  visual:
    origin:
      rpy: "0.0 1.082104136 0.0"
      xyz: "-0.357 -0.05 -0.3477"
    geometry:
      mesh: "adapterbox_bf_tech_klein/visual/cylinder_body_visual.dae"
      scale: "0.01 0.01 0.01"
    material: "silver"
  collision:
    origin:
      rpy: "0.0 0.0 0.0"
      xyz: "0.0 0.0 0.0"
    geometry:
      mesh: "adapterbox_bf_tech_klein/collision/cylinder_body_collision.stl"
      scale: "0.001 0.001 0.001"
  joints:
    cylinder_right_joint:
      origin:
        rpy: "0 0 0"
        xyz: "0 0 0"
      axis:
        xyz: "1 0 0"
      limit:
        effort: "100"
        lower: "0.0"
        upper: "3.141593"
        velocity: "100"

cylinder_rod_left:
  inertial:
    origin:
      rpy: "0.0 0.0 0.0"
      xyz: "0.0715 0.0 0.0"
    mass: "0.038777"
    inertia:
      ixx: "0.000000233"
      ixy: "0.0"
      ixz: "0.0"
      iyy: "0.000073796"
      iyz: "0.0"
      izz: "0.000073796"
  visual:
    origin:
      rpy: "0.0 -0.270526034 0.0"
      xyz: "0.3225 -0.0495 -0.1902"
    geometry:
      mesh: "adapterbox_bf_tech_klein/visual/cylinder_rod_visual.dae"
      scale: "0.01 0.01 0.01"
    material: "silver"
  collision:
    origin:
      rpy: "0.0 -0.34906585 0.0"
      xyz: "0.335 -0.0495 -0.1642"
    geometry:
      mesh: "adapterbox_bf_tech_klein/collision/cylinder_rod_collision.stl"
      scale: "0.001 0.001 0.001"

cylinder_rod_right:
  inertial:
    origin:
      rpy: "0.0 0.0 0.0"
      xyz: "0.0715 0.0 0.0"
    mass: "0.038777"
    inertia:
      ixx: "0.000000233"
      ixy: "0.0"
      ixz: "0.0"
      iyy: "0.000073796"
      iyz: "0.0"
      izz: "0.000073796"
  visual:
    origin:
      rpy: "0.0 -0.270526034 0.0"
      xyz: "0.3225 -0.0495 -0.1902"
    geometry:
      mesh: "adapterbox_bf_tech_klein/visual/cylinder_rod_visual.dae"
      scale: "0.01 0.01 0.01"
    material: "silver"
  collision:
    origin:
      rpy: "0.0 -0.34906585 0.0"
      xyz: "0.335 -0.0495 -0.1642"
    geometry:
      mesh: "adapterbox_bf_tech_klein/collision/cylinder_rod_collision.stl"
      scale: "0.001 0.001 0.001"


