box:
  inertial:
    origin:
      rpy: "-0.019 -0.018 -0.15444444"
      xyz: "-0.19786365477500727 0.28499999999999814 0.10499850115056943"
    mass: "29.18085733319406"
    inertia:
      ixx: "0.632523"
      ixy: "-0.0"
      ixz: "0.0499518"
      iyy: "0.3129864"
      iyz: "-0.0"
      izz: "0.7956252"
  visual:
    origin:
      rpy: "0 0 0"
      xyz: "0 0 0"
    geometry:
      mesh: "adapterbox/base_link.stl"
      scale: "0.001 0.001 0.001"
    material: "silver"
  collision:
    origin:
      rpy: "0 0 0"
      xyz: "0 0 0"
    geometry:
      mesh: "adapterbox/base_link.stl"
      scale: "0.001 0.001 0.001"
  joints:
    cover_joint:
      origin:
        rpy: "0 0 0"
        xyz: "-0.289622 0.0595 0.291782"
      axis:
        xyz: "0.0 1.0 0.0"
      limit:
        effort: "100"
        lower: "5.148721"
        upper: "6.283185"
        velocity: "100"
    lever_joint:
      origin:
        rpy: "0 0 0"
        xyz: "-0.051 0.0 0.1"
      axis:
        xyz: "0.0 1.0 0.0"
      limit:
        effort: "100"
        lower: "0.0"
        upper: "3.141593"
        velocity: "100"

cover:
  inertial:
    origin:
      rpy: "-0.015444444 -0.03 -0.15444444"
      xyz: "0.13419681438320717 0.2254999999999996 -0.0481548271949701"
    mass: "26.810171815154508"
    inertia:
      ixx: "0.6071664"
      ixy: "-0.0"
      ixz: "0.05935776"
      iyy: "0.22176384"
      iyz: "-0.0"
      izz: "0.78777696"
  visual:
    origin:
      rpy: "0 0 0"
      xyz: "0.289622 -0.0595 -0.291782"
    geometry:
      mesh: "adapterbox/Cover_1.stl"
      scale: "0.001 0.001 0.001"
    material: "silver"
  collision:
    origin:
      rpy: "0 0 0"
      xyz: "0.289622 -0.0595 -0.291782"
    geometry:
      mesh: "adapterbox/Cover_1.stl"
      scale: "0.001 0.001 0.001"

lever:
  inertial:
    origin:
      rpy: "0 0 0"
      xyz: "-0.014720727565339396 0.2850000242663596 8.230766698757996e-08"
    mass: "0.9500423291460965"
    inertia:
      ixx: "0.072964"
      ixy: "-0.0"
      ixz: "0.0"
      iyy: "0.000708"
      iyz: "-0.0"
      izz: "0.073633"
  visual:
    origin:
      rpy: "0 0 0"
      xyz: "0.051 -0.0 -0.1"
    geometry:
      mesh: "adapterbox/Lever_1.stl"
      scale: "0.001 0.001 0.001"
    material: "silver"
  collision:
    origin:
      rpy: "0 0 0"
      xyz: "0.051 -0.0 -0.1"
    geometry:
      mesh: "adapterbox/Lever_1.stl"
      scale: "0.001 0.001 0.001"

