adapter_plate:
  inertial:
    origin:
      rpy: "0.0 0.0 0.0"
      xyz: "0.051 -0.0 -0.05"
    mass: "2.5"
    inertia:
      ixx: "0.042015211"
      ixy: "0.0"
      ixz: "0.0"
      iyy: "0.027312107"
      iyz: "0.0"
      izz: "0.069256229"
  visual:
    origin:
      rpy: "0.0 0.0 0.0"
      xyz: "0.051 -0.0 -0.1"
    geometry:
      mesh: "adapter_bmt135_bmt172/visual/adapter_cover_bmt135_bmt172_visual.dae"
      scale: "0.01 0.01 0.01"
    material: "silver"
  collision:
    origin:
      rpy: "0.0 0.0 0.0"
      xyz: "0.051 -0.0 -0.1"
    geometry:
      mesh: "adapter_bmt135_bmt172/collision/adapter_cover_bmt135_bmt172_collision.stl"
      scale: "0.001 0.001 0.001"
  joints:
    box_joint:
      origin:
        rpy: "0.0 0.0 0.0"
        xyz: "-0.051 0.0 0.1"

cover_binder:
  inertial:
    origin:
      rpy: "0.0 0.436332313 0.0"
      xyz: "0.1 0.225 -0.1"
    mass: "2.0"
    inertia:
      ixx: "0.030996673"
      ixy: "0.0"
      ixz: "0.0"
      iyy: "0.011564673"
      iyz: "0.0"
      izz: "0.042488333"
  visual:
    origin:
      rpy: "0.0 1.308996939 0.0"
      xyz: "-0.181 -0.098 -0.355"
    geometry:
      mesh: "adapter_bmt135_bmt172/visual/cover_binder_bmt135_bmt172_visual.dae"
      scale: "0.01 0.01 0.01"
    material: "silver"
  collision:
    origin:
      rpy: "0.0 0.0 0.0"
      xyz: "0.3158 -0.098 -0.2937"
    geometry:
      mesh: "adapter_bmt135_bmt172/collision/cover_binder_bmt135_bmt172_collision.stl"
      scale: "0.001 0.001 0.001"
  joints:
    cover_joint:
      origin:
        rpy: "0.0 0.0 0.0"
        xyz: "0.0 0.0 0.0"