box:
  inertial:
    origin:
      rpy: "0.0 0.0 0.0"
      xyz: "-0.18786365477500727 0.28499999999999814 0.15499850115056943"
    mass: "9.07273"
    inertia:
      ixx: "0.1170147508224"
      ixy: "0.0"
      ixz: "0.0"
      iyy: "0.0553996845056"
      iyz: "0.0"
      izz: "0.1485738213376"
  visual:
    origin:
      rpy: "0 0 0"
      xyz: "0 0 0"
    geometry:
      mesh: "adapterbox_bf_tech_klein/visual/box_visual_v2.dae"
      scale: "0.01 0.01 0.01"
    material: "silver"
  collision:
    origin:
      rpy: "0 0 0"
      xyz: "0 0 0"
    geometry:
      mesh: "adapterbox_bf_tech_klein/collision/box_collision.stl"
      scale: "0.001 0.001 0.001"
  joints:
    cover_joint:
      origin:
        rpy: "0.0 0.0 0.0"
        xyz: "-0.289622 0.0595 0.291782"
      axis:
        xyz: "0.0 1.0 0.0"
      limit:
        effort: "100"
        lower: "-1.5708"
        upper: "0"
        velocity: "100"
    lever_joint:
      origin:
        rpy: "0 0 0"
        xyz: "-0.0540005 0.0 0.1030005"
      axis:
        xyz: "0.0 1.0 0.0"
      limit:
        effort: "100"
        lower: "0.0"
        upper: "3.141593"
        velocity: "100"
    cylinder_rod_left_joint:
      origin:
        rpy: "0 0.34906585 0"
        xyz: "-0.26 0.0495 0.26941"
      axis:
        xyz: "0 1 0"
      limit:
        effort: "100"
        lower: "-1.670796327"
        upper: "0.0"
        velocity: "100"
    cylinder_rod_right_joint:
      origin:
        rpy: "0 0.34906585 0"
        xyz: "-0.26 0.5185 0.26941"
      axis:
        xyz: "0 1 0"
      limit:
        effort: "100"
        lower: "-1.670796327"
        upper: "0.0"
        velocity: "100"

cover_frame:
  inertial:
    origin:
      rpy: "0.0 0.0 0.0"
      xyz: "0.14619681438320717 0.2254999999999996 -0.0431548271949701"
    mass: "2.799406"
    inertia:
      ixx: "46.105124864e-3"
      ixy: "0.000021816533203e-3"
      ixz: "2.1816533203e-17"
      iyy: "16.124355584e-3"
      iyz: "0.000010374246094e-3"
      izz: "58.971848704e-3"
  visual:
    origin:
      rpy: "0.0 1.308996939 0.0"
      xyz: "-0.20675 -0.0595 -0.3525"
    geometry:
      mesh: "adapterbox_bf_tech_klein/visual/cover_frame_visual.dae"
      scale: "0.01 0.01 0.01"
    material: "silver"
  collision:
    origin:
      rpy: "0.0 0.0 0.0"
      xyz: "0.289622 -0.0595 -0.291782"
    geometry:
      mesh: "adapterbox_bf_tech_klein/collision/cover_frame_collision.stl"
      scale: "0.001 0.001 0.001"
  joints:
    cylinder_body_left_joint:
      origin:
        rpy: "0 0.32 0"
        xyz: "0.2192 -0.0095 -0.094"
      axis:
        xyz: "0 1 0"
      limit:
        effort: "100"
        lower: "-1.570796327"
        upper: "0.0"
        velocity: "100"
    cylinder_body_right_joint:
      origin:
        rpy: "0 0.32 0"
        xyz: "0.2192 0.459 -0.094"
      axis:
        xyz: "0 1 0"
      limit:
        effort: "100"
        lower: "-1.570796327"
        upper: "0.0"
        velocity: "100"

lever:
  inertial:
    origin:
      rpy: "0.0 0.0 1.570796327"
      xyz: "-0.015 0.2850000242663596 0.0"
    mass: "0.760776"
    inertia:
      ixx: "0.05149"
      ixy: "-1.052e-15"
      ixz: "-9.811e-9"
      iyy: "0.0005332"
      iyz: "-1.629e-15"
      izz: "0.052"
  visual:
    origin:
      rpy: "0 0 0"
      xyz: "0.0125 -0.0475 -0.0125"
    geometry:
      mesh: "adapterbox_bf_tech_klein/visual/lever_visual.dae"
      scale: "0.01 0.01 0.01"
    material: "silver"
  collision:
    origin:
      rpy: "0 0 0"
      xyz: "0.0540005 -0.0 -0.1030005"
    geometry:
      mesh: "adapterbox_bf_tech_klein/collision/lever_collision.stl"
      scale: "0.001 0.001 0.001"

cylinder_body_left:
  inertial:
    origin:
      rpy: "0 0 0"
      xyz: "-0.075 0 0"
    mass: "0.187167"
    inertia:
      ixx: "0.0002285"
      ixy: "-1.396e-15"
      ixz: "-0.0001308"
      iyy: "0.0003057"
      iyz: "-1.35e-15"
      izz: "0.000083722904"
  visual:
    origin:
      rpy: "0.0 1.082104136 0.0"
      xyz: "-0.357 -0.05 -0.3477"
    geometry:
      mesh: "adapterbox_bf_tech_klein/visual/cylinder_body_visual.dae"
      scale: "0.01 0.01 0.01"
    material: "silver"
  collision:
    origin:
      rpy: "0.0 -0.35 0.0"
      xyz: "0.1325 -0.05 -0.1625"
    geometry:
      mesh: "adapterbox_bf_tech_klein/collision/cylinder_body_collision.stl"
      scale: "0.001 0.001 0.001"
  joints:
    cylinder_left_joint:
      origin:
        rpy: "0 0 0"
        xyz: "0.2 0.0 0.0"
      axis:
        xyz: "1 0 0"
      limit:
        effort: "100"
        lower: "0.0"
        upper: "0.95"
        velocity: "100"

cylinder_body_right:
  inertial:
    origin:
      rpy: "0 0 0"
      xyz: "-0.075 0 0"
    mass: "0.187167"
    inertia:
      ixx: "0.0002285"
      ixy: "-1.396e-15"
      ixz: "-0.0001308"
      iyy: "0.0003057"
      iyz: "-1.35e-15"
      izz: "0.000083722904"
  visual:
    origin:
      rpy: "0.0 1.082104136 0.0"
      xyz: "-0.357 -0.05 -0.3477"
    geometry:
      mesh: "adapterbox_bf_tech_klein/visual/cylinder_body_visual.dae"
      scale: "0.01 0.01 0.01"
    material: "silver"
  collision:
    origin:
      rpy: "0.0 0.0 0.0"
      xyz: "0.0 0.0 0.0"
    geometry:
      mesh: "adapterbox_bf_tech_klein/collision/cylinder_body_collision.stl"
      scale: "0.001 0.001 0.001"
  joints:
    cylinder_right_joint:
      origin:
        rpy: "0 0 0"
        xyz: "0 0 0"
      axis:
        xyz: "1 0 0"
      limit:
        effort: "100"
        lower: "0.0"
        upper: "3.141593"
        velocity: "100"

cylinder_rod_left:
  inertial:
    origin:
      rpy: "0 0 0"
      xyz: "0.049 0 0"
    mass: "0.038417"
    inertia:
      ixx: "0.00001"
      ixy: "0.0"
      ixz: "0.0"
      iyy: "0.00001"
      iyz: "0.0"
      izz: "0.00001"
  visual:
    origin:
      rpy: "0.0 -0.270526034 0.0"
      xyz: "0.3225 -0.0495 -0.1902"
    geometry:
      mesh: "adapterbox_bf_tech_klein/visual/cylinder_rod_visual.dae"
      scale: "0.01 0.01 0.01"
    material: "silver"
  collision:
    origin:
      rpy: "0.0 -0.34906585 0.0"
      xyz: "0.335 -0.0495 -0.1642"
    geometry:
      mesh: "adapterbox_bf_tech_klein/collision/cylinder_rod_collision.stl"
      scale: "0.001 0.001 0.001"

cylinder_rod_right:
  inertial:
    origin:
      rpy: "0 0 0"
      xyz: "0.049 0 0"
    mass: "0.038417"
    inertia:
      ixx: "0.00001"
      ixy: "0.0"
      ixz: "0.0"
      iyy: "0.00001"
      iyz: "0.0"
      izz: "0.00001"
  visual:
    origin:
      rpy: "0.0 -0.270526034 0.0"
      xyz: "0.3225 -0.0495 -0.1902"
    geometry:
      mesh: "adapterbox_bf_tech_klein/visual/cylinder_rod_visual.dae"
      scale: "0.01 0.01 0.01"
    material: "silver"
  collision:
    origin:
      rpy: "0.0 -0.34906585 0.0"
      xyz: "0.335 -0.0495 -0.1642"
    geometry:
      mesh: "adapterbox_bf_tech_klein/collision/cylinder_rod_collision.stl"
      scale: "0.001 0.001 0.001"


