adapter_plate:
  inertial:
    origin:
      rpy: "0 0 0"
      xyz: "-0.502428 0.284 0.285367"
    mass: "2.742074"
    inertia:
      ixx: "0.04095"
      ixy: "-1.023732e-6"
      ixz: "0.006486"
      iyy: "0.02592"
      iyz: "1.90736e-7"
      izz: "0.06322"
  visual:
    origin:
      rpy: "0 0 0"
      xyz: "0.051 -0.0 -0.1"
    geometry:
      mesh: "adapter_bmt135_bmt172/visual/adapter_cover_bmt135_bmt172_visual.dae"
      scale: "0.01 0.01 0.01"
    material: "silver"
  collision:
    origin:
      rpy: "0 0 0"
      xyz: "0.051 -0.0 -0.1"
    geometry:
      mesh: "adapter_bmt135_bmt172/collision/adapter_cover_bmt135_bmt172_collision.stl"
      scale: "0.001 0.001 0.001"
  joints:
    box_joint:
      origin:
        rpy: "0 0 0"
        xyz: "-0.051 0.0 0.1"

cover_binder:
  inertial:
    origin:
      rpy: "0 0 0"
      xyz: "-0.135 0.215 0.04"
    mass: "2.00847"
    inertia:
      ixx: "26.49227264e-3"
      ixy: "-0.00242880525e-3"
      ixz: "2.480113408e-3"
      iyy: "9.677550592e-3"
      iyz: "0.0029015125e-3"
      izz: "34.690670592e-3"
  visual:
    origin:
      rpy: "0.0 1.308996939 0.0"
      xyz: "-0.181 -0.098 -0.355"
    geometry:
      mesh: "adapter_bmt135_bmt172/visual/cover_binder_bmt135_bmt172_visual.dae"
      scale: "0.01 0.01 0.01"
    material: "silver"
  collision:
    origin:
      rpy: "0.0 0.0 0.0"
      xyz: "0.3158 -0.098 -0.2937"
    geometry:
      mesh: "adapter_bmt135_bmt172/collision/cover_binder_bmt135_bmt172_collision.stl"
      scale: "0.001 0.001 0.001"
  joints:
    cover_joint:
      origin:
        rpy: "0 0 0"
        xyz: "-0.026 0.0385 0.0018"