controller_manager:
  ros__parameters:
    update_rate: 100    # Hz

    # Publish all joint states -----------------------------------
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      publish_rate: 50

    # Position Controllers --------------------------------------
    BoxCover_Joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: BoxCover_Joint
      pid: {p: 100.0, i: 0.01, d: 10.0}
    BoxLever_Joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: BoxLever_Joint
      pid: {p: 100.0, i: 0.01, d: 10.0}
