version: "2.4"

################################################################################

services:
  ros2_foxy:
    hostname: modproft
    runtime: ${DOCKER_RUNTIME}
    privileged: true
    environment:
      # Pass host user information.
      - HOST_USER=${USER}
      - HOST_UID=1000
      - HOST_GID=1000
      # Display X Server GUI.
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      # Configure Nvidia Docker interface.
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_REQUIRE_CUDA=cuda>=9.0
    build:
      context: ../
      dockerfile: ./docker/dockerfile
    volumes:
      # Map ROS workspace folders.
      - ./scripts/:/root/scripts/
      - ../ros2_ws/src/:/root/ModProFT/src/
      - ../ROS_Foxy_Utility_Code/src/:/root/ROS_Foxy_Utility_Code/src/
      - ../install_init/:/root/install_init/
      - ../kill/:/root/kill/
      - ../run/:/root/run/
      - ../../tools/pycharm/:/opt/pycharm
      - ../../tools/clion/:/opt/clion
      - ../share/:/root/share/
      # Grant display access to X Server.
      - /tmp/.X11-unix:/tmp/.X11-unix
      # Grant bus access to FlexBE App.
      #- /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      # Grant access to serial usb ports for u2d2
      - /dev/for_docker:/dev/for_docker
      - ../overwrite/ur_robot_driver/include/ur_robot_driver/hardware_interface.hpp:/root/ur_driver/src/ur_robot_driver/include/ur_robot_driver/hardware_interface.hpp
      - ../overwrite/ur_robot_driver/resources/ros_control.urscript:/root/ur_driver/src/ur_robot_driver/resources/ros_control.urscript
      - ../overwrite/ur_robot_driver/src/hardware_interface.cpp:/root/ur_driver/src/ur_robot_driver/src/hardware_interface.cpp
      - ../overwrite/ur_description/urdf/ur.urdf.xacro:/root/ur_driver/src/ur_description/urdf/ur.urdf.xacro
      - ../overwrite/ur_description/urdf/ur_macro.xacro:/root/ur_driver/src/ur_description/urdf/ur_macro.xacro
    devices:
      - '/dev:/dev'
    ports:
      - 50001:50001
      - 50002:50002
      - 50003:50003
      - 50004:50004
    extra_hosts:
      - "ros_ros2_test:127.0.0.1"   # Seems that it might be needed for ROS networking
      - "ros_ros2_test:192.168.137.201"
      #- "o2as-matlab-machine:192.168.0.2"
      #- "o2as-shibata:192.168.0.3"
    command: /root/scripts/keep-container-running.sh
    
