camera:
  inertial:
    origin:
      rpy: "-1.57 1.57 0"
      xyz: "0 0 0"
    mass: "0.303"
    inertia:
      ixx: "0.0001"
      ixy: "0.0"
      ixz: "0.0"
      iyy: "0.0001"
      iyz: "0.0"
      izz: "0.0001"
  visual:
    origin:
      rpy: "-1.57 1.57 0"
      xyz: "0 0 0"
    geometry:
      mesh: "Canon_Powershot_G7_MKIII/canon_powershot_g7_mkiii_collision.stl"
      scale: "0.001 0.001 0.001"
    material: "silver"
  collision:
    origin:
      rpy: "-1.57 1.57 0"
      xyz: "0 0 0"
    geometry:
      mesh: "Canon_Powershot_G7_MKIII/canon_powershot_g7_mkiii_visual.stl"
      scale: "0.001 0.001 0.001"
  virtual:
    visual:
      geometry:
        mesh: "Debug_Mesh/camera_arrow.stl"
        scale: "0.001 0.001 0.001"
  
  sensor:
    type: "depth"
    always_on: "false"
    update_rate: 30.0
    name: "Canon_Powershot_G7_MKIII"
    horizontal_fov: 1.047198
    image:
      width: 640
      height: 480
      format: R8G8B8
      clip:
        near: 0.05
        far: 3.0
      distortion:
        k1: 0.0
        k2: 0.0
        k3: 0.0
        p1: 0.0
        p2: 0.0
        center: 0.5 0.5
    hack_baseline: 0.07
    min_depth: 0.01
  
  joints:
    attachment_joint:
      origin:
        rpy: "0.0 -1.57 0.0"
        xyz: "-0.045 0.05 0.08"
    virtual_joint:
      origin:
        rpy: "-1.57 0.0 -1.57"
        xyz: "0.057 0 0.032"