table:
  inertial:
    origin:
      rpy: "0 0 0"
      xyz: "0 0 0"
    mass: "100.0"
    inertia:
      ixx: "8.666666667"
      ixy: "0.0"
      ixz: "0.0"
      iyy: "2.416666667"
      iyz: "0.0"
      izz: "10.416666667"
  visual:
    origin:
      rpy: "0.0 0.0 0.0"
      xyz: "0.0 0.0 0.0"
    geometry:
      mesh: ""
      scale: "0.5 1.0 0.2"
    material: "silver"
  collision:
    origin:
      rpy: "0 0 0"
      xyz: "0 0 0"
    geometry:
      mesh: ""
      scale: "0.5 1.0 0.2"
  
  joints:
    attachment_joint:
      origin:
        rpy: "0.0 0.0 0.0"
        xyz: "0.0 0.0 0.101"
    tabletop_joint:
      origin:
        rpy: "0.0 0.0 0.0"
        xyz: "0.0 0.0 0.101"