table:
  inertial:
    origin:
      rpy: "0 0 0"
      xyz: "0 0 0"
    mass: "0.01"
    inertia:
      ixx: "0.0001"
      ixy: "0.0"
      ixz: "0.0"
      iyy: "0.0001"
      iyz: "0.0"
      izz: "0.0001"
  visual:
    origin:
      rpy: "0.0 0.0 0.0"
      xyz: "0.0 0.0 0.0"
    geometry:
      mesh: ""
      scale: "0.25 0.25 0.2"
    material: "silver"
  collision:
    origin:
      rpy: "0 0 0"
      xyz: "0 0 0"
    geometry:
      mesh: ""
      scale: "0.25 0.25 0.2"
  
  joints:
    attachment_joint:
      origin:
        rpy: "0.0 0.0 0.0"
        xyz: "0.0 0.0 0.101"
    tabletop_joint:
      origin:
        rpy: "0.0 0.0 0.0"
        xyz: "0.0 0.0 0.101"